FROM nginx:latest

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ENV PROJECT_DIR=/frontend

COPY frontend $PROJECT_DIR 

WORKDIR $PROJECT_DIR

RUN ls -l

RUN mkdir -p /etc/nginx/sites-available/
RUN mkdir -p /etc/nginx/sites-enabled/
RUN mkdir -p /root/certs/


COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.proj.conf /etc/nginx/sites-available/

ARG backend_host=127.0.0.1:8000
ENV BACKEND_HOST=${backend_host}

RUN cp $PROJECT_DIR/ssl/certificate.crt /root/certs/certificate.crt
RUN cp $PROJECT_DIR/ssl/private.key /root/certs/private.key

RUN envsubst '${BACKEND_HOST},${BACKEND_HOST}' < /etc/nginx/sites-available/nginx.proj.conf > /etc/nginx/sites-available/nginx.proj.conf

RUN ln -s /etc/nginx/sites-available/nginx.proj.conf  /etc/nginx/sites-enabled/

WORKDIR $PROJECT_DIR

EXPOSE 80 443

