FROM python:3.6.2

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ENV PROJECT_DIR=/backend
WORKDIR $PROJECT_DIR

COPY backend $PROJECT_DIR

RUN ls -l

RUN mkdir -p /var/log/uwsgi/

RUN pip install pipenv -i https://pypi.douban.com/simple
RUN pipenv install --system --deploy

WORKDIR $PROJECT_DIR/sj

EXPOSE 8000 9191